version: '3'
services:

  app:
    build:
      context: .
      dockerfile: $APP_DOCKER
      args:
        APP_IMG: $APP_IMG

    container_name: app
    restart: always

    networks:
      - infra

    ports:
      - $APP_PORT:$APP_PORT
      - 9229:9229
      - 7575:7575

    volumes:
      - static:/static:z

networks:
  infra:

volumes:
  static: