version: '3'
services:

  db:
    image: ${PG_IMG}

    container_name: db
    restart: always

    networks:
      - infra

    ports:
      - ${PG_PORT}:${PG_PORT}

    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}

    volumes:
      - db_data:/var/lib/postgresql/data:z


networks:
  infra:

volumes:
  db_data:
