version: '3'
services:

  scylla:
    image: ${SCYLLA_IMG}

    container_name: scylla
    restart: always

    networks:
      - infra

    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
      - 10000:10000

    volumes:
      - scylla_data:/var/lib/scylla:z


networks:
  infra:

volumes:
  scylla_data:
